util.AddNetworkString("SpellbookCollected")
util.AddNetworkString("StartSpellRandomizer")
util.AddNetworkString("FinalizeSpell")
util.AddNetworkString("SpellCastFail")
util.AddNetworkString("ClearSpellUI")
